"use client"

import { motion } from "framer-motion"

export default function PerpetualEngine() {
    return (
        <section className="engine-section">
            <div className="container">
                <div className="engine-grid">
                    <div className="engine-visual">
                        <MechanismDiagram />
                    </div>
                    <div className="engine-text">
                        <motion.h2
                            className="accent"
                            initial={{ opacity: 0, x: 20 }}
                            whileInView={{ opacity: 1, x: 0 }}
                            viewport={{ once: true }}
                            transition={{ duration: 1 }}
                        >
                            The Perpetual Engine.
                        </motion.h2>
                        <motion.blockquote
                            initial={{ opacity: 0 }}
                            whileInView={{ opacity: 1 }}
                            viewport={{ once: true }}
                            transition={{ duration: 1, delay: 0.3 }}
                        >
                            "True privacy should not have a subscription fee. The Key Protocol is sustained by the <span className="accent">$PRIVACY</span> token on the Pump.fun network.
                            We utilize the creator fees generated by $PRIVACY volume to subsidize gas costs for every message sent on the network. By holding $PRIVACY, you are not just an investor; you are a Patron of privacy."
                        </motion.blockquote>
                    </div>
                </div>
            </div>
        </section>
    )
}

function MechanismDiagram() {
    return (
        <motion.svg
            viewBox="0 0 400 300"
            className="engine-svg"
            initial={{ opacity: 0, scale: 0.9 }}
            whileInView={{ opacity: 1, scale: 1 }}
            viewport={{ once: true }}
            transition={{ duration: 1.5 }}
        >
            {/* Coin */}
            <motion.circle
                cx="100" cy="150" r="45"
                stroke="var(--accent)" strokeWidth="1.5" fill="transparent"
                animate={{ rotate: 360 }}
                transition={{ duration: 15, repeat: Infinity, ease: "linear" }}
            />
            <motion.circle
                cx="100" cy="150" r="35"
                stroke="var(--accent)" strokeWidth="0.5" fill="transparent"
                strokeDasharray="4 4"
                animate={{ rotate: -360 }}
                transition={{ duration: 20, repeat: Infinity, ease: "linear" }}
            />
            <text x="50" y="155" fill="var(--accent)" className="mono" style={{ fontSize: '14px' }}>$PRIVACY</text>

            {/* Flow line */}
            <motion.path
                d="M 150 150 L 250 150"
                stroke="var(--accent)" strokeWidth="1" strokeDasharray="6 6"
                animate={{ strokeDashoffset: -24 }}
                transition={{ duration: 2, repeat: Infinity, ease: "linear" }}
            />

            {/* Machine / App */}
            <motion.rect
                x="250" y="100" width="100" height="100"
                stroke="var(--ink)" fill="transparent" strokeWidth="1"
                initial={{ pathLength: 0 }}
                whileInView={{ pathLength: 1 }}
                transition={{ duration: 2 }}
            />
            <text x="270" y="155" fill="var(--ink)" className="mono" style={{ fontSize: '12px' }}>THE APP</text>

            {/* Messages coming out */}
            <motion.path
                d="M 310 100 L 310 40 M 340 100 L 340 60"
                stroke="var(--signal)" strokeWidth="1"
                initial={{ opacity: 0 }}
                animate={{ opacity: [0, 1, 0], y: [0, -20, -40] }}
                transition={{ duration: 3, repeat: Infinity, ease: "easeOut" }}
            />
            <motion.path
                d="M 280 100 L 280 50"
                stroke="var(--signal)" strokeWidth="1"
                initial={{ opacity: 0 }}
                animate={{ opacity: [0, 1, 0], y: [0, -15, -30] }}
                transition={{ duration: 2.5, repeat: Infinity, delay: 1, ease: "easeOut" }}
            />

            {/* Ornaments */}
            <motion.path
                d="M 50 150 Q 100 50 150 150"
                stroke="var(--signal)" strokeWidth="0.2" fill="transparent" strokeDasharray="2 2"
                opacity="0.3"
            />
        </motion.svg>
    )
}
